### ISSUE TITLE
Running on mobile devices

### ISSUE THREAD

**Issue by lsilvs** [cvdlab/react-planner#90]
HI, congrats for the project. The tool is very handy and easy to use.

I would like to use it to draw a floorplan using a tablet but it doesn't seem possible once the touch event doesn't correspond to the mouse event.

Do you guys see a way to manage that?

Cheers,
Lucas

**Comment by danilosalvati** [comment]
Hi @lsilvs,
Thank you for having tried our library :smile: 
A complete mobile interface requires a lot of work to do (perhaps we should use another paradigm to help users with drawings, because drawing on a small screen such as the one in a tablet is not like drawing on a pc monitor...). As a consequence for now we won't work on it (probably we will provide a good interface for drawing in mobile devices in the future...)

**Comment by lsilvs** [comment]
Hi @danilosalvati,
Thanks for your reply.

I end up tweaking the code for experimental purpose. I forked the project and just pushed my commit.
If you guys could take a look and give me any feedback would be great.

https://github.com/lsilvs/react-planner/commit/889b172689137788fbf1c1ea5d383dfa3d334b6b

I could prepare a Pul Request if you like.

Cheers,
Lucas

**Comment by danilosalvati** [comment]
Thank you for the interest @lsilvs, I will have a look at that code :+1:

**Comment by danilosalvati** [comment]
Hi @lsilvs,
We have checked your code, but it has still a lot of graphical bugs (for example every time you try to move the drawing area you lose all selected objects, or when you try to draw a line fron the top to the bottom you trigger the reload action for chrome mobile).
Perhaps in the future we will found out a better interaction to exploit mobile devices, but it will need a lot of more work to do.
